# Generated by Django 5.0.4 on 2024-05-07 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0002_companyinfo_faq_news_vacancy_contact_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='vacancy',
            name='need',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
