# Generated by Django 5.0.4 on 2024-05-11 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0006_delete_departmentmedicine'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='department',
            name='address',
        ),
        migrations.AddField(
            model_name='department',
            name='medicines',
            field=models.ManyToManyField(blank=True, related_name='departments', to='pharmacy.medicines'),
        ),
    ]
