# Generated by Django 5.0.4 on 2024-05-12 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0009_sale_medicine_sale_quantity_delete_saleitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='сost',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
    ]
