# Generated by Django 5.0.4 on 2024-05-12 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0010_sale_сost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='сost',
            field=models.FloatField(),
        ),
    ]
