# Generated by Django 5.0.4 on 2024-05-12 15:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0012_sale_cost_prom'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sale',
            old_name='сost',
            new_name='price',
        ),
        migrations.RenameField(
            model_name='sale',
            old_name='cost_prom',
            new_name='price_prom',
        ),
    ]
