# Generated by Django 5.0.4 on 2024-05-13 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0013_rename_сost_sale_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='no',
            field=models.CharField(max_length=255),
        ),
    ]
