# Generated by Django 5.0.4 on 2024-05-13 10:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0014_alter_department_no'),
    ]

    operations = [
    ]
