# Generated by Django 5.0.4 on 2024-05-13 10:41

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0015_auto_20240513_1339'),
    ]

    operations = [
        migrations.AddField(
            model_name='departmentmedicine',
            name='close',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='departmentmedicine',
            name='open',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
