# Generated by Django 5.0.4 on 2024-05-13 10:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0016_departmentmedicine_close_departmentmedicine_open'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='departmentmedicine',
            name='close',
        ),
        migrations.RemoveField(
            model_name='departmentmedicine',
            name='open',
        ),
    ]
