# Generated by Django 5.0.4 on 2024-05-13 10:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0020_department_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='department',
            name='date',
        ),
    ]
