# Generated by Django 5.0.4 on 2024-05-13 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0021_remove_department_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='date',
            field=models.TimeField(default='10:51:24.543425'),
        ),
    ]
