# Generated by Django 5.0.4 on 2024-05-13 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0022_department_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='department',
            old_name='date',
            new_name='open',
        ),
        migrations.AddField(
            model_name='department',
            name='close',
            field=models.TimeField(default='10:51:24.543425'),
        ),
    ]
