# Generated by Django 5.0.4 on 2024-05-13 10:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0023_rename_date_department_open_department_close'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='department',
            name='close',
        ),
        migrations.RemoveField(
            model_name='department',
            name='open',
        ),
    ]
