# Generated by Django 5.0.4 on 2024-05-13 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0024_remove_department_close_remove_department_open'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='close',
            field=models.TimeField(default='10:51:24.543425'),
        ),
        migrations.AddField(
            model_name='department',
            name='open',
            field=models.TimeField(default='10:51:24.543425'),
        ),
    ]
