# Generated by Django 5.0.4 on 2024-05-19 20:48

import pharmacy.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0027_remove_cartitem_cart_remove_cartitem_medicine_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='age',
            field=models.PositiveSmallIntegerField(validators=[pharmacy.models.User.validate_age]),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(max_length=15, validators=[pharmacy.models.User.validate_phone]),
        ),
    ]
